/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './app/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './app/auth/reset-password'
import { Route as AuthLoginRouteImport } from './app/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/auth/forgot-password'
import { Route as AuthenticatedDashboardRouteImport } from './app/_authenticated/dashboard'
import { Route as AuthenticatedUsersIndexRouteImport } from './app/_authenticated/users/index'
import { Route as AuthenticatedUsersCreateRouteImport } from './app/_authenticated/users/create'
import { Route as AuthenticatedUsersUserIdRouteImport } from './app/_authenticated/users/$userId'
import { Route as AuthenticatedUsersUserIdShowRouteImport } from './app/_authenticated/users/$userId.show'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './app/_authenticated/users/$userId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdShowRoute =
  AuthenticatedUsersUserIdShowRouteImport.update({
    id: '/show',
    path: '/show',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/users/$userId/show': typeof AuthenticatedUsersUserIdShowRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/users/$userId/show': typeof AuthenticatedUsersUserIdShowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/users/$userId/show': typeof AuthenticatedUsersUserIdShowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/users/$userId'
    | '/users/create'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId/show'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/users/$userId'
    | '/users/create'
    | '/users'
    | '/users/$userId/edit'
    | '/users/$userId/show'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_authenticated/'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/create'
    | '/_authenticated/users/'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/users/$userId/show'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/show': {
      id: '/_authenticated/users/$userId/show'
      path: '/show'
      fullPath: '/users/$userId/show'
      preLoaderRoute: typeof AuthenticatedUsersUserIdShowRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
  }
}

interface AuthenticatedUsersUserIdRouteChildren {
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedUsersUserIdShowRoute: typeof AuthenticatedUsersUserIdShowRoute
}

const AuthenticatedUsersUserIdRouteChildren: AuthenticatedUsersUserIdRouteChildren =
  {
    AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
    AuthenticatedUsersUserIdShowRoute: AuthenticatedUsersUserIdShowRoute,
  }

const AuthenticatedUsersUserIdRouteWithChildren =
  AuthenticatedUsersUserIdRoute._addFileChildren(
    AuthenticatedUsersUserIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRouteWithChildren
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRouteWithChildren,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
