/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthenticatedRouteImport } from './app/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './app/_authenticated/index'
import { Route as AuthResetPasswordRouteImport } from './app/auth/reset-password'
import { Route as AuthLoginRouteImport } from './app/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './app/auth/forgot-password'
import { Route as AuthenticatedDashboardRouteImport } from './app/_authenticated/dashboard'
import { Route as AuthenticatedWarehousesIndexRouteImport } from './app/_authenticated/warehouses/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './app/_authenticated/users/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './app/_authenticated/suppliers/index'
import { Route as AuthenticatedSubclassesIndexRouteImport } from './app/_authenticated/subclasses/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './app/_authenticated/roles/index'
import { Route as AuthenticatedRawMaterialsIndexRouteImport } from './app/_authenticated/raw-materials/index'
import { Route as AuthenticatedProcessesIndexRouteImport } from './app/_authenticated/processes/index'
import { Route as AuthenticatedMachinesIndexRouteImport } from './app/_authenticated/machines/index'
import { Route as AuthenticatedInventoryStockIndexRouteImport } from './app/_authenticated/inventory-stock/index'
import { Route as AuthenticatedInventoryMovementsIndexRouteImport } from './app/_authenticated/inventory-movements/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './app/_authenticated/customers/index'
import { Route as AuthenticatedClassesIndexRouteImport } from './app/_authenticated/classes/index'
import { Route as AuthenticatedUsersCreateRouteImport } from './app/_authenticated/users/create'
import { Route as AuthenticatedUsersUserIdRouteImport } from './app/_authenticated/users/$userId'
import { Route as AuthenticatedSuppliersCreateRouteImport } from './app/_authenticated/suppliers/create'
import { Route as AuthenticatedSuppliersSupplierIdRouteImport } from './app/_authenticated/suppliers/$supplierId'
import { Route as AuthenticatedCustomersCreateRouteImport } from './app/_authenticated/customers/create'
import { Route as AuthenticatedUsersUserIdShowRouteImport } from './app/_authenticated/users/$userId.show'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './app/_authenticated/users/$userId.edit'
import { Route as AuthenticatedSuppliersSupplierIdShowRouteImport } from './app/_authenticated/suppliers/$supplierId.show'
import { Route as AuthenticatedSuppliersSupplierIdEditRouteImport } from './app/_authenticated/suppliers/$supplierId.edit'
import { Route as AuthenticatedCustomersCustomerIdShowRouteImport } from './app/_authenticated/customers/$customerId.show'
import { Route as AuthenticatedCustomersCustomerIdEditRouteImport } from './app/_authenticated/customers/$customerId.edit'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWarehousesIndexRoute =
  AuthenticatedWarehousesIndexRouteImport.update({
    id: '/warehouses/',
    path: '/warehouses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubclassesIndexRoute =
  AuthenticatedSubclassesIndexRouteImport.update({
    id: '/subclasses/',
    path: '/subclasses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRawMaterialsIndexRoute =
  AuthenticatedRawMaterialsIndexRouteImport.update({
    id: '/raw-materials/',
    path: '/raw-materials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProcessesIndexRoute =
  AuthenticatedProcessesIndexRouteImport.update({
    id: '/processes/',
    path: '/processes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMachinesIndexRoute =
  AuthenticatedMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockIndexRoute =
  AuthenticatedInventoryStockIndexRouteImport.update({
    id: '/inventory-stock/',
    path: '/inventory-stock/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryMovementsIndexRoute =
  AuthenticatedInventoryMovementsIndexRouteImport.update({
    id: '/inventory-movements/',
    path: '/inventory-movements/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClassesIndexRoute =
  AuthenticatedClassesIndexRouteImport.update({
    id: '/classes/',
    path: '/classes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersCreateRoute =
  AuthenticatedUsersCreateRouteImport.update({
    id: '/users/create',
    path: '/users/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersCreateRoute =
  AuthenticatedSuppliersCreateRouteImport.update({
    id: '/suppliers/create',
    path: '/suppliers/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdRoute =
  AuthenticatedSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCreateRoute =
  AuthenticatedCustomersCreateRouteImport.update({
    id: '/customers/create',
    path: '/customers/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersUserIdShowRoute =
  AuthenticatedUsersUserIdShowRouteImport.update({
    id: '/show',
    path: '/show',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedUsersUserIdRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdShowRoute =
  AuthenticatedSuppliersSupplierIdShowRouteImport.update({
    id: '/show',
    path: '/show',
    getParentRoute: () => AuthenticatedSuppliersSupplierIdRoute,
  } as any)
const AuthenticatedSuppliersSupplierIdEditRoute =
  AuthenticatedSuppliersSupplierIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedSuppliersSupplierIdRoute,
  } as any)
const AuthenticatedCustomersCustomerIdShowRoute =
  AuthenticatedCustomersCustomerIdShowRouteImport.update({
    id: '/customers/$customerId/show',
    path: '/customers/$customerId/show',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdEditRoute =
  AuthenticatedCustomersCustomerIdEditRouteImport.update({
    id: '/customers/$customerId/edit',
    path: '/customers/$customerId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRouteWithChildren
  '/suppliers/create': typeof AuthenticatedSuppliersCreateRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory-movements': typeof AuthenticatedInventoryMovementsIndexRoute
  '/inventory-stock': typeof AuthenticatedInventoryStockIndexRoute
  '/machines': typeof AuthenticatedMachinesIndexRoute
  '/processes': typeof AuthenticatedProcessesIndexRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/subclasses': typeof AuthenticatedSubclassesIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/warehouses': typeof AuthenticatedWarehousesIndexRoute
  '/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/customers/$customerId/show': typeof AuthenticatedCustomersCustomerIdShowRoute
  '/suppliers/$supplierId/edit': typeof AuthenticatedSuppliersSupplierIdEditRoute
  '/suppliers/$supplierId/show': typeof AuthenticatedSuppliersSupplierIdShowRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/users/$userId/show': typeof AuthenticatedUsersUserIdShowRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRouteWithChildren
  '/suppliers/create': typeof AuthenticatedSuppliersCreateRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/users/create': typeof AuthenticatedUsersCreateRoute
  '/classes': typeof AuthenticatedClassesIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/inventory-movements': typeof AuthenticatedInventoryMovementsIndexRoute
  '/inventory-stock': typeof AuthenticatedInventoryStockIndexRoute
  '/machines': typeof AuthenticatedMachinesIndexRoute
  '/processes': typeof AuthenticatedProcessesIndexRoute
  '/raw-materials': typeof AuthenticatedRawMaterialsIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/subclasses': typeof AuthenticatedSubclassesIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/warehouses': typeof AuthenticatedWarehousesIndexRoute
  '/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/customers/$customerId/show': typeof AuthenticatedCustomersCustomerIdShowRoute
  '/suppliers/$supplierId/edit': typeof AuthenticatedSuppliersSupplierIdEditRoute
  '/suppliers/$supplierId/show': typeof AuthenticatedSuppliersSupplierIdShowRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/users/$userId/show': typeof AuthenticatedUsersUserIdShowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/create': typeof AuthenticatedCustomersCreateRoute
  '/_authenticated/suppliers/$supplierId': typeof AuthenticatedSuppliersSupplierIdRouteWithChildren
  '/_authenticated/suppliers/create': typeof AuthenticatedSuppliersCreateRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRouteWithChildren
  '/_authenticated/users/create': typeof AuthenticatedUsersCreateRoute
  '/_authenticated/classes/': typeof AuthenticatedClassesIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/inventory-movements/': typeof AuthenticatedInventoryMovementsIndexRoute
  '/_authenticated/inventory-stock/': typeof AuthenticatedInventoryStockIndexRoute
  '/_authenticated/machines/': typeof AuthenticatedMachinesIndexRoute
  '/_authenticated/processes/': typeof AuthenticatedProcessesIndexRoute
  '/_authenticated/raw-materials/': typeof AuthenticatedRawMaterialsIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/subclasses/': typeof AuthenticatedSubclassesIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/warehouses/': typeof AuthenticatedWarehousesIndexRoute
  '/_authenticated/customers/$customerId/edit': typeof AuthenticatedCustomersCustomerIdEditRoute
  '/_authenticated/customers/$customerId/show': typeof AuthenticatedCustomersCustomerIdShowRoute
  '/_authenticated/suppliers/$supplierId/edit': typeof AuthenticatedSuppliersSupplierIdEditRoute
  '/_authenticated/suppliers/$supplierId/show': typeof AuthenticatedSuppliersSupplierIdShowRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/users/$userId/show': typeof AuthenticatedUsersUserIdShowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/customers/create'
    | '/suppliers/$supplierId'
    | '/suppliers/create'
    | '/users/$userId'
    | '/users/create'
    | '/classes'
    | '/customers'
    | '/inventory-movements'
    | '/inventory-stock'
    | '/machines'
    | '/processes'
    | '/raw-materials'
    | '/roles'
    | '/subclasses'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/show'
    | '/suppliers/$supplierId/edit'
    | '/suppliers/$supplierId/show'
    | '/users/$userId/edit'
    | '/users/$userId/show'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/'
    | '/customers/create'
    | '/suppliers/$supplierId'
    | '/suppliers/create'
    | '/users/$userId'
    | '/users/create'
    | '/classes'
    | '/customers'
    | '/inventory-movements'
    | '/inventory-stock'
    | '/machines'
    | '/processes'
    | '/raw-materials'
    | '/roles'
    | '/subclasses'
    | '/suppliers'
    | '/users'
    | '/warehouses'
    | '/customers/$customerId/edit'
    | '/customers/$customerId/show'
    | '/suppliers/$supplierId/edit'
    | '/suppliers/$supplierId/show'
    | '/users/$userId/edit'
    | '/users/$userId/show'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/_authenticated/'
    | '/_authenticated/customers/create'
    | '/_authenticated/suppliers/$supplierId'
    | '/_authenticated/suppliers/create'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/create'
    | '/_authenticated/classes/'
    | '/_authenticated/customers/'
    | '/_authenticated/inventory-movements/'
    | '/_authenticated/inventory-stock/'
    | '/_authenticated/machines/'
    | '/_authenticated/processes/'
    | '/_authenticated/raw-materials/'
    | '/_authenticated/roles/'
    | '/_authenticated/subclasses/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/users/'
    | '/_authenticated/warehouses/'
    | '/_authenticated/customers/$customerId/edit'
    | '/_authenticated/customers/$customerId/show'
    | '/_authenticated/suppliers/$supplierId/edit'
    | '/_authenticated/suppliers/$supplierId/show'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/users/$userId/show'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/warehouses/': {
      id: '/_authenticated/warehouses/'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AuthenticatedWarehousesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subclasses/': {
      id: '/_authenticated/subclasses/'
      path: '/subclasses'
      fullPath: '/subclasses'
      preLoaderRoute: typeof AuthenticatedSubclassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raw-materials/': {
      id: '/_authenticated/raw-materials/'
      path: '/raw-materials'
      fullPath: '/raw-materials'
      preLoaderRoute: typeof AuthenticatedRawMaterialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processes/': {
      id: '/_authenticated/processes/'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof AuthenticatedProcessesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/machines/': {
      id: '/_authenticated/machines/'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof AuthenticatedMachinesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-stock/': {
      id: '/_authenticated/inventory-stock/'
      path: '/inventory-stock'
      fullPath: '/inventory-stock'
      preLoaderRoute: typeof AuthenticatedInventoryStockIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory-movements/': {
      id: '/_authenticated/inventory-movements/'
      path: '/inventory-movements'
      fullPath: '/inventory-movements'
      preLoaderRoute: typeof AuthenticatedInventoryMovementsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/classes/': {
      id: '/_authenticated/classes/'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/create': {
      id: '/_authenticated/users/create'
      path: '/users/create'
      fullPath: '/users/create'
      preLoaderRoute: typeof AuthenticatedUsersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/create': {
      id: '/_authenticated/suppliers/create'
      path: '/suppliers/create'
      fullPath: '/suppliers/create'
      preLoaderRoute: typeof AuthenticatedSuppliersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/$supplierId': {
      id: '/_authenticated/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/suppliers/$supplierId'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/create': {
      id: '/_authenticated/customers/create'
      path: '/customers/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof AuthenticatedCustomersCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId/show': {
      id: '/_authenticated/users/$userId/show'
      path: '/show'
      fullPath: '/users/$userId/show'
      preLoaderRoute: typeof AuthenticatedUsersUserIdShowRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedUsersUserIdRoute
    }
    '/_authenticated/suppliers/$supplierId/show': {
      id: '/_authenticated/suppliers/$supplierId/show'
      path: '/show'
      fullPath: '/suppliers/$supplierId/show'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdShowRouteImport
      parentRoute: typeof AuthenticatedSuppliersSupplierIdRoute
    }
    '/_authenticated/suppliers/$supplierId/edit': {
      id: '/_authenticated/suppliers/$supplierId/edit'
      path: '/edit'
      fullPath: '/suppliers/$supplierId/edit'
      preLoaderRoute: typeof AuthenticatedSuppliersSupplierIdEditRouteImport
      parentRoute: typeof AuthenticatedSuppliersSupplierIdRoute
    }
    '/_authenticated/customers/$customerId/show': {
      id: '/_authenticated/customers/$customerId/show'
      path: '/customers/$customerId/show'
      fullPath: '/customers/$customerId/show'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdShowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId/edit': {
      id: '/_authenticated/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedSuppliersSupplierIdRouteChildren {
  AuthenticatedSuppliersSupplierIdEditRoute: typeof AuthenticatedSuppliersSupplierIdEditRoute
  AuthenticatedSuppliersSupplierIdShowRoute: typeof AuthenticatedSuppliersSupplierIdShowRoute
}

const AuthenticatedSuppliersSupplierIdRouteChildren: AuthenticatedSuppliersSupplierIdRouteChildren =
  {
    AuthenticatedSuppliersSupplierIdEditRoute:
      AuthenticatedSuppliersSupplierIdEditRoute,
    AuthenticatedSuppliersSupplierIdShowRoute:
      AuthenticatedSuppliersSupplierIdShowRoute,
  }

const AuthenticatedSuppliersSupplierIdRouteWithChildren =
  AuthenticatedSuppliersSupplierIdRoute._addFileChildren(
    AuthenticatedSuppliersSupplierIdRouteChildren,
  )

interface AuthenticatedUsersUserIdRouteChildren {
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedUsersUserIdShowRoute: typeof AuthenticatedUsersUserIdShowRoute
}

const AuthenticatedUsersUserIdRouteChildren: AuthenticatedUsersUserIdRouteChildren =
  {
    AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
    AuthenticatedUsersUserIdShowRoute: AuthenticatedUsersUserIdShowRoute,
  }

const AuthenticatedUsersUserIdRouteWithChildren =
  AuthenticatedUsersUserIdRoute._addFileChildren(
    AuthenticatedUsersUserIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersCreateRoute: typeof AuthenticatedCustomersCreateRoute
  AuthenticatedSuppliersSupplierIdRoute: typeof AuthenticatedSuppliersSupplierIdRouteWithChildren
  AuthenticatedSuppliersCreateRoute: typeof AuthenticatedSuppliersCreateRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRouteWithChildren
  AuthenticatedUsersCreateRoute: typeof AuthenticatedUsersCreateRoute
  AuthenticatedClassesIndexRoute: typeof AuthenticatedClassesIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedInventoryMovementsIndexRoute: typeof AuthenticatedInventoryMovementsIndexRoute
  AuthenticatedInventoryStockIndexRoute: typeof AuthenticatedInventoryStockIndexRoute
  AuthenticatedMachinesIndexRoute: typeof AuthenticatedMachinesIndexRoute
  AuthenticatedProcessesIndexRoute: typeof AuthenticatedProcessesIndexRoute
  AuthenticatedRawMaterialsIndexRoute: typeof AuthenticatedRawMaterialsIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedSubclassesIndexRoute: typeof AuthenticatedSubclassesIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWarehousesIndexRoute: typeof AuthenticatedWarehousesIndexRoute
  AuthenticatedCustomersCustomerIdEditRoute: typeof AuthenticatedCustomersCustomerIdEditRoute
  AuthenticatedCustomersCustomerIdShowRoute: typeof AuthenticatedCustomersCustomerIdShowRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersCreateRoute: AuthenticatedCustomersCreateRoute,
  AuthenticatedSuppliersSupplierIdRoute:
    AuthenticatedSuppliersSupplierIdRouteWithChildren,
  AuthenticatedSuppliersCreateRoute: AuthenticatedSuppliersCreateRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRouteWithChildren,
  AuthenticatedUsersCreateRoute: AuthenticatedUsersCreateRoute,
  AuthenticatedClassesIndexRoute: AuthenticatedClassesIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedInventoryMovementsIndexRoute:
    AuthenticatedInventoryMovementsIndexRoute,
  AuthenticatedInventoryStockIndexRoute: AuthenticatedInventoryStockIndexRoute,
  AuthenticatedMachinesIndexRoute: AuthenticatedMachinesIndexRoute,
  AuthenticatedProcessesIndexRoute: AuthenticatedProcessesIndexRoute,
  AuthenticatedRawMaterialsIndexRoute: AuthenticatedRawMaterialsIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedSubclassesIndexRoute: AuthenticatedSubclassesIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWarehousesIndexRoute: AuthenticatedWarehousesIndexRoute,
  AuthenticatedCustomersCustomerIdEditRoute:
    AuthenticatedCustomersCustomerIdEditRoute,
  AuthenticatedCustomersCustomerIdShowRoute:
    AuthenticatedCustomersCustomerIdShowRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
